name: Daily RSS to Blog

on:
  schedule:
    - cron: '0 18 * * *'  # Runs every day at 8 PM South African Time (UTC +2)
  workflow_dispatch:  # This allows you to manually trigger the workflow from the GitHub UI

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This checks out your code so it can run the script
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Use Python 3.8 (or change to your preferred version)

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install the required libraries
    
    - name: Run the script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Uses the secret you stored
        MEDIUM_ACCESS_TOKEN: ${{ secrets.MEDIUM_ACCESS_TOKEN }}  # Uses the Medium token secret
      run: |
        python script.py  # Run your Python script
